std_msgs/Header header

int32 A_rows
int32 A_cols
float32[] A_data

int32 B_rows
int32 B_cols
float32[] B_data

int32 R_rows
int32 R_cols
float32[] R_data

int32 C_rows
int32 C_cols
float32[] C_data

int32 Q_rows
int32 Q_cols
float32[] Q_data

int32 S_rows
int32 S_cols
float32[] S_data

int32 K_rows
int32 K_cols
float32[] K_data

int32 mu_size
float32[] mu_data

int32 mu_p_size
float32[] mu_p_data

int32 S_p_rows
int32 S_p_cols
float32[] S_p_data
