% plots for the PIDs
clc;
close all;
clear all;

load('Pid Plotting Data.mat')

figure(1)
% plot z with the setpoint.
% [ax,h1,h2] = plotyy(Time, True_z, Time, Pid_z_Kp, 'plot') ;
% hold(ax(1))
% plot(ax(1), Time, setpointz, 'm')
% hold(ax(2))
% plot(ax(2), Time, Pid_z_Kd,'r')

% fixing the Kd data file
x = Pid_z_Kd;
x(Pid_z_Kd == 0 ) = [];
xt = Time;
xt(Pid_z_Kd == 0 ) = [];
Kd_z_interpolated = interp1(xt,x,Time);

commanded_thrust = Kd_z_interpolated*10 + Pid_z_Kd*10;
% plot z with the setpoint.
[ax,h1,h2] = plotyy(Time, True_z, Time, -commanded_thrust, 'plot') ;

hold(ax(1))
plot(ax(1), Time, setpointz, 'm')
hold(ax(2), 'on')
% plot(ax(2), Time, Kd_z_interpolated*10,'r')
% hold(ax(2), 'off')
set(ax(1),  'YLimMode', 'manual', 'YTickMode', 'auto',...
            'YMinorTick', 'on', 'Fontsize', 12, ...
            'FontWeight', 'bold', ...
            'YColor', 'k')
     
set(ax(2), 'YLimMode', 'auto', 'YTickMode', 'auto',...
            'YMinorTick', 'on', 'Fontsize', 12, ...
            'FontWeight', 'bold', ...
            'YColor', 'k')
set(ax(2),'Box','Off')
set(ax(1),'Box','Off')

ylabel(ax(1), 'Commanded Position [meters]',...
               'Fontsize', 15, ...
               'FontWeight', 'normal');
ylabel(ax(2), 'Commanded Thrust [Percentage of Thrust]',...
               'Fontsize', 15, ...
               'FontWeight', 'normal', ...
               'color', 'k');
xlabel('Time [seconds]',...
             'Fontsize', 15, ...
             'FontWeight', 'normal');
legend('True Elevation [m]', ...
       'Set Elevation [m]', ...
       'Commanded Thrust')
                                

figure(2)
plot(Time, Pid_z_Kp*10, 'b', Time, Kd_z_interpolated*10, 'r')
set(gca,    'YLimMode', 'auto', 'YTickMode', 'auto',...
            'YMinorTick', 'on', 'Fontsize', 12, ...
            'FontWeight', 'bold', ...
            'YColor', 'k')
        
xlabel('Time [seconds]',...
             'Fontsize', 15, ...
             'FontWeight', 'normal');

ylabel(gca, 'Control Signal',...
               'Fontsize', 15, ...
               'FontWeight', 'normal', ...
               'color', 'k');
         
legend('Proportional Error Signal', ...
       'Derivative Error Signal');

figure(3)
setpointx = setpointz*0;
% fixing the Kd data file
x = PidPitch_kd(1:end-15);
x(PidPitch_kd(1:end-15) == 0 ) = [];
xt = Time;
xt(PidPitch_kd(1:end-15) == 0) = [];
Kd_pitch_interpolated = interp1(xt,x,Time);

pitch_command = rad2deg(Kd_pitch_interpolated) + rad2deg(PidPitch_kp(1:end-15)) + rad2deg(PidPitch_ki(1:end-15));
pitch_command(abs(pitch_command) > 20) = 20;
% plot z with the setpoint.
[ax,h1,h2] = plotyy(Time, True_x, Time, pitch_command, 'plot') 

hold(ax(1));
plot(ax(1), Time, setpointx, 'm')
% hold(ax(2), 'on')
% plot(ax(2), Time, rad2deg(PidPitch_ki(1:end-15)), 'g', Time, rad2deg(Kd_pitch_interpolated),'r' )
set(ax(1),  'YLimMode', 'auto', 'YTickMode', 'auto',...
            'YMinorTick', 'on', 'Fontsize', 12, ...
            'FontWeight', 'bold', ...
            'YColor', 'k', 'ylim', [-1 1])
     
set(ax(2), 'YLimMode', 'auto', 'YTickMode', 'auto',...
            'YMinorTick', 'on', 'Fontsize', 12, ...
            'FontWeight', 'bold', ...
            'YColor', 'k', 'ylim', [-30 30])
set(ax(2),'Box','Off')
set(ax(1),'Box','Off')

ylabel(ax(1), 'Commanded X Position [meters]',...
               'Fontsize', 15, ...
               'FontWeight', 'normal');
ylabel(ax(2), 'Commanded Pitch [Degrees]',...
               'Fontsize', 15, ...
               'FontWeight', 'normal', ...
               'color', 'k');
xlabel('Time [seconds]',...
             'Fontsize', 15, ...
             'FontWeight', 'normal');
legend('True X Position [m]', ...
       'Set X Position [m]', ...
       'Commanded Pitch [degrees]')
   
figure(4)
plot(Time, rad2deg(PidPitch_kp(1:end-15)), 'b',...
     Time, rad2deg(Kd_pitch_interpolated), 'r',...
     Time, rad2deg(PidPitch_ki(1:end-15)), 'g')
 
set(gca,    'YLimMode', 'auto', 'YTickMode', 'auto',...
            'YMinorTick', 'on', 'Fontsize', 12, ...
            'FontWeight', 'bold', ...
            'YColor', 'k')
        
xlabel('Time [seconds]',...
             'Fontsize', 15, ...
             'FontWeight', 'normal');

ylabel(gca, 'Pitch Control Signal [Degrees]',...
               'Fontsize', 15, ...
               'FontWeight', 'normal', ...
               'color', 'k');
         
legend('Proportional Error Signal', ...
       'Derivative Error Signal', ...
       'Integral Error Signal');


figure(5)
setpointx = setpointz*0;
% fixing the Kd data file
x = PidRoll_kd(1:end-15);
x(PidRoll_kd(1:end-15) == 0 ) = [];
xt = Time;
xt(PidRoll_kd(1:end-15) == 0) = [];
Kd_roll_interpolated = interp1(xt,x,Time);


roll_command = rad2deg(Kd_roll_interpolated) + rad2deg(PidRoll_kp(1:end-15)) + rad2deg(PidRoll_kp(1:end-15));
roll_command(abs(roll_command) > 20) = 20;

% plot z with the setpoint.
[ax,h1,h2] = plotyy(Time, True_y, Time, roll_command, 'plot') ;
hold(ax(1))
plot(ax(1), Time, setpointx, 'm')
hold(ax(2), 'on')
%plot(ax(2), Time, rad2deg(PidRoll_ki(1:end-15)), 'g', Time, rad2deg(Kd_roll_interpolated),'r' )
set(ax(1),  'YLimMode', 'auto', 'YTickMode', 'auto',...
            'YMinorTick', 'on', 'Fontsize', 12, ...
            'FontWeight', 'bold', ...
            'YColor', 'k', 'ylim', [-1 1])
     
set(ax(2), 'YLimMode', 'auto', 'YTickMode', 'auto',...
            'YMinorTick', 'on', 'Fontsize', 12, ...
            'FontWeight', 'bold', ...
            'YColor', 'k', 'ylim', [-30 30])
set(ax(2),'Box','Off')
set(ax(1),'Box','Off')

ylabel(ax(1), 'Commanded Y Position [meters]',...
               'Fontsize', 15, ...
               'FontWeight', 'normal');
ylabel(ax(2), 'Commanded Roll [Degrees]',...
               'Fontsize', 15, ...
               'FontWeight', 'normal', ...
               'color', 'k');
xlabel('Time [seconds]',...
             'Fontsize', 15, ...
             'FontWeight', 'normal');
legend('True Y Position [m]', ...
       'Set Y Position [m]', ...
       'Commanded Roll [degrees]')
       
   
figure(6)
plot(Time, rad2deg(PidRoll_kp(1:end-15)), 'b',...
     Time, rad2deg(Kd_roll_interpolated), 'r',...
     Time, rad2deg(PidRoll_ki(1:end-15)), 'g')
 
set(gca,    'YLimMode', 'auto', 'YTickMode', 'auto',...
            'YMinorTick', 'on', 'Fontsize', 12, ...
            'FontWeight', 'bold', ...
            'YColor', 'k')
        
xlabel('Time [seconds]',...
             'Fontsize', 15, ...
             'FontWeight', 'normal');

ylabel(gca, 'Roll Control Signal [Degrees]',...
               'Fontsize', 15, ...
               'FontWeight', 'normal', ...
               'color', 'k');
         
legend('Proportional Error Signal', ...
       'Derivative Error Signal', ...
       'Integral Error Signal');
axis([0 70 -50 50])