// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model_pose.proto

#ifndef PROTOBUF_model_5fpose_2eproto__INCLUDED
#define PROTOBUF_model_5fpose_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace wavesim_msgs {
namespace msgs {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_model_5fpose_2eproto();
void protobuf_AssignDesc_model_5fpose_2eproto();
void protobuf_ShutdownFile_model_5fpose_2eproto();

class ModelPose;

// ===================================================================

class ModelPose : public ::google::protobuf::Message {
 public:
  ModelPose();
  virtual ~ModelPose();

  ModelPose(const ModelPose& from);

  inline ModelPose& operator=(const ModelPose& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ModelPose& default_instance();

  void Swap(ModelPose* other);

  // implements Message ----------------------------------------------

  ModelPose* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ModelPose& from);
  void MergeFrom(const ModelPose& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string model_name = 1;
  inline bool has_model_name() const;
  inline void clear_model_name();
  static const int kModelNameFieldNumber = 1;
  inline const ::std::string& model_name() const;
  inline void set_model_name(const ::std::string& value);
  inline void set_model_name(const char* value);
  inline void set_model_name(const char* value, size_t size);
  inline ::std::string* mutable_model_name();
  inline ::std::string* release_model_name();
  inline void set_allocated_model_name(::std::string* model_name);

  // required double x = 2;
  inline bool has_x() const;
  inline void clear_x();
  static const int kXFieldNumber = 2;
  inline double x() const;
  inline void set_x(double value);

  // required double y = 3;
  inline bool has_y() const;
  inline void clear_y();
  static const int kYFieldNumber = 3;
  inline double y() const;
  inline void set_y(double value);

  // required double z = 4;
  inline bool has_z() const;
  inline void clear_z();
  static const int kZFieldNumber = 4;
  inline double z() const;
  inline void set_z(double value);

  // required double roll = 5;
  inline bool has_roll() const;
  inline void clear_roll();
  static const int kRollFieldNumber = 5;
  inline double roll() const;
  inline void set_roll(double value);

  // required double pitch = 6;
  inline bool has_pitch() const;
  inline void clear_pitch();
  static const int kPitchFieldNumber = 6;
  inline double pitch() const;
  inline void set_pitch(double value);

  // required double yaw = 7;
  inline bool has_yaw() const;
  inline void clear_yaw();
  static const int kYawFieldNumber = 7;
  inline double yaw() const;
  inline void set_yaw(double value);

  // @@protoc_insertion_point(class_scope:wavesim_msgs.msgs.ModelPose)
 private:
  inline void set_has_model_name();
  inline void clear_has_model_name();
  inline void set_has_x();
  inline void clear_has_x();
  inline void set_has_y();
  inline void clear_has_y();
  inline void set_has_z();
  inline void clear_has_z();
  inline void set_has_roll();
  inline void clear_has_roll();
  inline void set_has_pitch();
  inline void clear_has_pitch();
  inline void set_has_yaw();
  inline void clear_has_yaw();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* model_name_;
  double x_;
  double y_;
  double z_;
  double roll_;
  double pitch_;
  double yaw_;
  friend void  protobuf_AddDesc_model_5fpose_2eproto();
  friend void protobuf_AssignDesc_model_5fpose_2eproto();
  friend void protobuf_ShutdownFile_model_5fpose_2eproto();

  void InitAsDefaultInstance();
  static ModelPose* default_instance_;
};
// ===================================================================


// ===================================================================

// ModelPose

// required string model_name = 1;
inline bool ModelPose::has_model_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ModelPose::set_has_model_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ModelPose::clear_has_model_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ModelPose::clear_model_name() {
  if (model_name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    model_name_->clear();
  }
  clear_has_model_name();
}
inline const ::std::string& ModelPose::model_name() const {
  // @@protoc_insertion_point(field_get:wavesim_msgs.msgs.ModelPose.model_name)
  return *model_name_;
}
inline void ModelPose::set_model_name(const ::std::string& value) {
  set_has_model_name();
  if (model_name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    model_name_ = new ::std::string;
  }
  model_name_->assign(value);
  // @@protoc_insertion_point(field_set:wavesim_msgs.msgs.ModelPose.model_name)
}
inline void ModelPose::set_model_name(const char* value) {
  set_has_model_name();
  if (model_name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    model_name_ = new ::std::string;
  }
  model_name_->assign(value);
  // @@protoc_insertion_point(field_set_char:wavesim_msgs.msgs.ModelPose.model_name)
}
inline void ModelPose::set_model_name(const char* value, size_t size) {
  set_has_model_name();
  if (model_name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    model_name_ = new ::std::string;
  }
  model_name_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:wavesim_msgs.msgs.ModelPose.model_name)
}
inline ::std::string* ModelPose::mutable_model_name() {
  set_has_model_name();
  if (model_name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    model_name_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:wavesim_msgs.msgs.ModelPose.model_name)
  return model_name_;
}
inline ::std::string* ModelPose::release_model_name() {
  clear_has_model_name();
  if (model_name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = model_name_;
    model_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void ModelPose::set_allocated_model_name(::std::string* model_name) {
  if (model_name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete model_name_;
  }
  if (model_name) {
    set_has_model_name();
    model_name_ = model_name;
  } else {
    clear_has_model_name();
    model_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:wavesim_msgs.msgs.ModelPose.model_name)
}

// required double x = 2;
inline bool ModelPose::has_x() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ModelPose::set_has_x() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ModelPose::clear_has_x() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ModelPose::clear_x() {
  x_ = 0;
  clear_has_x();
}
inline double ModelPose::x() const {
  // @@protoc_insertion_point(field_get:wavesim_msgs.msgs.ModelPose.x)
  return x_;
}
inline void ModelPose::set_x(double value) {
  set_has_x();
  x_ = value;
  // @@protoc_insertion_point(field_set:wavesim_msgs.msgs.ModelPose.x)
}

// required double y = 3;
inline bool ModelPose::has_y() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void ModelPose::set_has_y() {
  _has_bits_[0] |= 0x00000004u;
}
inline void ModelPose::clear_has_y() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void ModelPose::clear_y() {
  y_ = 0;
  clear_has_y();
}
inline double ModelPose::y() const {
  // @@protoc_insertion_point(field_get:wavesim_msgs.msgs.ModelPose.y)
  return y_;
}
inline void ModelPose::set_y(double value) {
  set_has_y();
  y_ = value;
  // @@protoc_insertion_point(field_set:wavesim_msgs.msgs.ModelPose.y)
}

// required double z = 4;
inline bool ModelPose::has_z() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void ModelPose::set_has_z() {
  _has_bits_[0] |= 0x00000008u;
}
inline void ModelPose::clear_has_z() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void ModelPose::clear_z() {
  z_ = 0;
  clear_has_z();
}
inline double ModelPose::z() const {
  // @@protoc_insertion_point(field_get:wavesim_msgs.msgs.ModelPose.z)
  return z_;
}
inline void ModelPose::set_z(double value) {
  set_has_z();
  z_ = value;
  // @@protoc_insertion_point(field_set:wavesim_msgs.msgs.ModelPose.z)
}

// required double roll = 5;
inline bool ModelPose::has_roll() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void ModelPose::set_has_roll() {
  _has_bits_[0] |= 0x00000010u;
}
inline void ModelPose::clear_has_roll() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void ModelPose::clear_roll() {
  roll_ = 0;
  clear_has_roll();
}
inline double ModelPose::roll() const {
  // @@protoc_insertion_point(field_get:wavesim_msgs.msgs.ModelPose.roll)
  return roll_;
}
inline void ModelPose::set_roll(double value) {
  set_has_roll();
  roll_ = value;
  // @@protoc_insertion_point(field_set:wavesim_msgs.msgs.ModelPose.roll)
}

// required double pitch = 6;
inline bool ModelPose::has_pitch() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void ModelPose::set_has_pitch() {
  _has_bits_[0] |= 0x00000020u;
}
inline void ModelPose::clear_has_pitch() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void ModelPose::clear_pitch() {
  pitch_ = 0;
  clear_has_pitch();
}
inline double ModelPose::pitch() const {
  // @@protoc_insertion_point(field_get:wavesim_msgs.msgs.ModelPose.pitch)
  return pitch_;
}
inline void ModelPose::set_pitch(double value) {
  set_has_pitch();
  pitch_ = value;
  // @@protoc_insertion_point(field_set:wavesim_msgs.msgs.ModelPose.pitch)
}

// required double yaw = 7;
inline bool ModelPose::has_yaw() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void ModelPose::set_has_yaw() {
  _has_bits_[0] |= 0x00000040u;
}
inline void ModelPose::clear_has_yaw() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void ModelPose::clear_yaw() {
  yaw_ = 0;
  clear_has_yaw();
}
inline double ModelPose::yaw() const {
  // @@protoc_insertion_point(field_get:wavesim_msgs.msgs.ModelPose.yaw)
  return yaw_;
}
inline void ModelPose::set_yaw(double value) {
  set_has_yaw();
  yaw_ = value;
  // @@protoc_insertion_point(field_set:wavesim_msgs.msgs.ModelPose.yaw)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace msgs
}  // namespace wavesim_msgs

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_model_5fpose_2eproto__INCLUDED
